### PR TITLE
Changes In the Setup Files

### PR DESCRIPTION
**Pull request by Shahid-Bagwan**
### **Made changes in the Html & Css files.**

**- added header section.**
**- added headline section.**
**- designed header & headline section.**
**- updated readme file : added information related to the project.**

### CODE REVIEW

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @Shahid-Bagwan , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project that has a couple of areas that need improvement.
- The branch name you have chosen does not provide a clear indication of the feature or action being implemented. It is important to use descriptive branch names that accurately describe the purpose of the branch. For example, instead of a generic name like "feature1," consider using names like "**created\_sidebar**" or "**added\_comments\_section**" that convey the specific feature or action being worked on. :pray: Please rename the branch to a meaningful name. Check out this [official document](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) for further help. :+1:

- The title of your pull request lacks professionalism. It is essential to have a clear and meaningful title that accurately describes the purpose of the pull request. Consider using titles like "Create a Sidebar for Mobile Menu" or "Add Comments Section for User" that provide a concise summary of the changes made. :+1: Please change the PR title which describes what you did in this PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Shahid-Bagwan** [comment]
## Pull Request: Professionalizing Changes in HTML & CSS Files

### Changes Made
- Added a header section to the HTML file.
- Added a headline section to the HTML file.
- Designed the header and headline sections in the CSS file.
- Updated the README file with relevant project information.

### Description
This pull request aims to professionalize the changes made in the HTML and CSS files. The following modifications have been implemented:

#### HTML Changes
1. Added a header section to provide consistent navigation across the website.
2. Included a headline section to grab user attention and provide a brief introduction.

#### CSS Changes
1. Designed the header section to enhance the visual appeal and improve user experience.
2. Styled the headline section to ensure readability and a coherent design with the rest of the webpage.

#### README Update
Added information related to the project in the README file. This includes relevant details about the purpose, features, and usage of the project. The updated README aims to provide comprehensive documentation for developers and users.

### Additional Information
Any relevant background context or information regarding the changes made can be included here.

Please review this pull request and provide any feedback or suggestions for improvement.

**Comment by Shahid-Bagwan** [comment]
@shahadat3669 above is the PR

**Comment by shahadat3669** [comment]
Hi @Shahid-Bagwan. your branch name is invalid.

| Your  | Professional |
|---------------------|-----------------------|
| image | image |

**Pull request closed without merging**
